[project]
name = "wtftw_core"
version = "0.3.1"
authors = ["Simon Wollwage"]

[dependencies]
bitflags = "0.5"
rustc-serialize = "*"
log = "*"
num = "*"
libc = "*"
dylib = "*"

[lib]
name = "wtftw_core"
path = "src/wtftw.rs"
crate-type = ["rlib"]
